# Generated by Django 2.2.6 on 2019-10-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='DatasourceDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='DateDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='AdvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impressions')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.CampaignDim', verbose_name='Campaign')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.DatasourceDim', verbose_name='Data source')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.DateDim')),
            ],
        ),
    ]
